FROM alekslitvinenk/dind


WORKDIR /init-app
RUN apk add --no-cache py-pip python3-dev libffi-dev openssl-dev gcc libc-dev make
RUN pip3 install docker-compose
COPY docker-init.sh ./
RUN  chmod +x docker-init.sh
COPY . .
EXPOSE 80
ENTRYPOINT ["./docker-init.sh"]